spring.application.name=communitysync 

# PostgreSQL
spring.datasource.url=jdbc:postgresql://192.168.1.227:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=AndreiM03
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Spring Security generates a password in console, but hard-code it for now
#spring.security.user.name=user   #am sters dependenta din pom.xml pentru a putea folosi si testa post request
#spring.security.user.password=user

# Server port
server.port=8080